// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package authentication

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthenticationPluginClient is the client API for AuthenticationPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthenticationPluginClient interface {
	// Attempts to authenticate a user
	Authenticate(ctx context.Context, in *AuthenticationRequest, opts ...grpc.CallOption) (*AuthenticationResponse, error)
}

type authenticationPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthenticationPluginClient(cc grpc.ClientConnInterface) AuthenticationPluginClient {
	return &authenticationPluginClient{cc}
}

func (c *authenticationPluginClient) Authenticate(ctx context.Context, in *AuthenticationRequest, opts ...grpc.CallOption) (*AuthenticationResponse, error) {
	out := new(AuthenticationResponse)
	err := c.cc.Invoke(ctx, "/proto.AuthenticationPlugin/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticationPluginServer is the server API for AuthenticationPlugin service.
// All implementations must embed UnimplementedAuthenticationPluginServer
// for forward compatibility
type AuthenticationPluginServer interface {
	// Attempts to authenticate a user
	Authenticate(context.Context, *AuthenticationRequest) (*AuthenticationResponse, error)
	mustEmbedUnimplementedAuthenticationPluginServer()
}

// UnimplementedAuthenticationPluginServer must be embedded to have forward compatible implementations.
type UnimplementedAuthenticationPluginServer struct {
}

func (UnimplementedAuthenticationPluginServer) Authenticate(context.Context, *AuthenticationRequest) (*AuthenticationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedAuthenticationPluginServer) mustEmbedUnimplementedAuthenticationPluginServer() {}

// UnsafeAuthenticationPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthenticationPluginServer will
// result in compilation errors.
type UnsafeAuthenticationPluginServer interface {
	mustEmbedUnimplementedAuthenticationPluginServer()
}

func RegisterAuthenticationPluginServer(s grpc.ServiceRegistrar, srv AuthenticationPluginServer) {
	s.RegisterService(&AuthenticationPlugin_ServiceDesc, srv)
}

func _AuthenticationPlugin_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationPluginServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthenticationPlugin/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationPluginServer).Authenticate(ctx, req.(*AuthenticationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthenticationPlugin_ServiceDesc is the grpc.ServiceDesc for AuthenticationPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthenticationPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AuthenticationPlugin",
	HandlerType: (*AuthenticationPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _AuthenticationPlugin_Authenticate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authentication.proto",
}
